// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Hounded_Heart.Models.Data;

#nullable disable

namespace Hounded_Heart.Models.PostgresMigrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260605_AddIsDeletedToPreRegistrations")]
    partial class AddIsDeletedToPreRegistrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // This is a simplified designer file. In production, you would include the full model snapshot.
            // For now, we just need it to exist for EF Core to recognize the migration.
#pragma warning restore 612, 618
        }
    }
}
