<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Hounded_Heart.Api\Hounded_Heart.Api.csproj" />
    <ProjectReference Include="..\Hounded_Heart.Services\Hounded_Heart.Services.csproj" />
    <ProjectReference Include="..\Hounded_Heart.Models\Hounded_Heart.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
