// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Hounded_Heart.Models.Data;

#nullable disable

namespace Hounded_Heart.Models.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608_FixEmailVerificationColumn")]
    partial class FixEmailVerificationColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Snapshot model - inherits from AppDbContextModelSnapshot
#pragma warning restore 612, 618
        }
    }
}
